format = """
[╭──](white)\
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$golang\
$helm\
$java\
$cmake\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$python\
$ruby\
$rust\
$swift\
$terraform\
$aws\
$gcloud\
$azure\
$battery               
[╰──❯ ](white)"""

add_newline = true

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[username]
format = " [$user]($style)"
style_user = "#94DDCD"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname ]($style)"
trim_at = "-"
style = "#78CCF6"
disabled = false

[directory]
truncation_length = 5
format = "in [$path]($style)[$lock_symbol]($lock_style) "
style = "#C0C9CE"

[cmd_duration]
min_time = 8_000
format = " took [$duration]($style)"


